config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #--=== 首頁 ===--#
  root 'welcome#index'

  #--=== 前台 ===--#

  # 商品 #
  resources :products do
    member do
      post :add_to_cart
      post :add_to_wish_list
      post :remove_from_wish_list
      post :setup_currency
    end

    # 搜索 #
    collection do
      get :search
    end
  end

  # 購物車 #
  resources :carts do
    collection do
      delete :clear # 清空購物車
      post :checkout # 下訂
    end
  end

  # 訂單 #
  resources :orders do
    member do
      post :pay_with_paypal # 使用 PayPal 付款
      post :apply_to_cancel # 申請取消訂單
    end
  end

  resources :cart_items

  #--=== 使用者專區 ===--#
  namespace :account do
    # 用戶中心 #
    resources :users
    # 訂單歷程 #
    resources :orders
    # 收藏清單 #
    resources :products do
      member do
        post :add_to_cart
        post :remove_from_wish_list
      end
    end
  end


  #--=== 管理員專區 ===--#
  namespace :admin do

    # 訂單管理 #
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end

    # 品牌 #
    resources :brands do
      member do
        post :publish
        post :hide
      end
    end


    # 類型 #
    resources :category_groups do
      member do
        post :publish
        post :hide
      end
    end

    # 分類 #
    resources :categories do
      member do
        post :publish
        post :hide
      end
    end

    # 商品 #
    resources :products do
      member do
        post :publish
        post :hide
        post :chosen
      end
    end

    # 首頁 Covers #
    resources :intros do
      member do
        post :publish
        post :hide
      end
    end
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
  # 新增/修改欄位限制與提示 #
  validates :name, presence: true

  # 關聯 #
  has_many :products

  # 發佈 / 隱藏 #
  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  # 上傳品牌 Logo 圖 #
  mount_uploader :logo, ImageUploader

  # Scope #
  scope :published, -> { where(is_hidden: false) }

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
  # 使用者必須登入
  before_action :authenticate_user!
  # 使用者必須是 admin 身份
  before_action :admin_required
  # 後台頁面排版
  layout "admin"

  def index
    @brands = Brand.all.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @brand = Brand.find(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to admin_brands_path
    else
      render :new
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(brand_params)
      redirect_to admin_brands_path
    else
      render :edit
    end
  end

  # 發佈
  def publish
    @brand = Brand.find(params[:id])
    @brand.publish!
    redirect_to :back
  end

  # 隱藏
  def hide
    @brand = Brand.find(params[:id])
    @brand.hide!
    redirect_to :back
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :description, :logo, :is_hidden)
  end

end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
  # 判斷品牌隱藏狀態，顯示 Public/Hidden 狀態
  def render_brand_status(brand)
    if brand.is_hidden
      content_tag(:span, "", :class => "fa fa-lock fa-fw")
    else
      content_tag(:span, "", :class => "fa fa-globe fa-fw")
    end
  end

  # 判斷品牌隱藏狀態，顯示 Publish/Hide 按鈕
  def render_brand_publish_or_hide(brand)
    if brand.is_hidden
      link_to(t('btn-publish'), publish_admin_brand_path(brand), :method => :post, :class => 'btn btn-sm btn-default')
    else
      link_to(t('btn-hide'), hide_admin_brand_path(brand), :method => :post, :class => 'btn btn-sm btn-default')
    end
  end

  # 判斷品牌 Logo，顯示圖片或尚無圖片訊息
  def render_brand_logo(brand)
    if brand.logo.present?
      image_tag(brand.logo.other.url)
    else
      t('notice-no-image')
    end
  end

end

app/views/admin/brands/_form.html.erb
<div class="col-md-10 col-md-offset-1 admin-data-box">
  <hr style="size:2px" />
  <%= simple_form_for [:admin, @brand] do |f| %>
    <%= f.input :name, :label => t('f-brand-name'), input_html: { class: 'width-50' } %>
    <% if @brand.logo.present?%>
      <%= image_tag(@brand.logo.other.url) %>
    <% end %>
    <%= f.input :logo, as: :file, :label => t('f-brand-logo') %>
    <%= f.input :description, :label => t('f-brand-description'), input_html: { class: 'height-200' } %>
    <span class="hidden-box"><%= f.input :is_hidden, :label => t('f-hide') %></span>
    <div class="form-actions">
      <%= f.submit t('f-submit'), class: 'btn btn-md btn-default' %>
    </div>
  <% end %>
</div>

app/views/admin/brands/edit.html.erb
<!--=== 修改品牌 ===-->
<h2><span class="fa fa-pencil-square-o"></span> <%= t('brand-edit') %></h2>
<%= render('form') %>

app/views/admin/brands/index.html.erb
<!--=== 頁面標題 ===-->
<h2><%= t('brand-index') %></h2>

<!--=== 新增品牌 ===-->
<div class="pull-right">
  <%= link_to(t('btn-brand-new'), new_admin_brand_path, :class => 'btn btn-md btn-info')%>
</div>

<!--=== 品牌列表 ===-->
<table class="table">
  <!--=== 品牌列表標題 ===-->
  <thead>
    <tr>
      <th><%= t('f-brand-name') %></th>
      <!-- <th><%= t('f-brand-logo') %></th> -->
      <th><%= t('f-brand-description') %></th>
      <th><%= t('f-options') %></th>
    </tr>
  </thead>

  <!--=== 品牌列表內容 ===-->
  <% @brands.each do |brand| %>
    <tr>
      <td><%= render_brand_status(brand) %> <%= link_to(brand.name, admin_brand_path(brand)) %></td>
      <!-- <td><%= render_brand_logo(brand) %></td> -->
      <td class="description-box"><%= simple_format(brand.description) %></td>
      <!--=== 操作選項 ===-->
      <td class="action-box">
        <!-- 編輯 -->
        <%= link_to(edit_admin_brand_path(brand), class: "btn btn-md btn-default") do %>
          <span class="fa fa-pencil"></span>
        <% end %>

        <!-- 發佈 / 隱藏 -->
        <!-- <%= render_brand_publish_or_hide(brand) %> -->
        <% if brand.is_hidden %>
          <%= link_to(publish_admin_brand_path(brand), :method => :post, class: "btn btn-md btn-default show-btn") do %>
            <span class="fa fa-eye"></span>
          <% end %>
        <% else %>
          <%= link_to(hide_admin_brand_path(brand), :method => :post, data: { confirm: "確定隱藏該品牌？" }, class: "btn btn-md btn-default") do %>
            <span class="fa fa-eye-slash"></span>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<div class="col-md-12">
  <div class="text-center">
    <%= will_paginate @brands, renderer: BootstrapPagination::Rails, :previous_label => t('previous-label'), :next_label => t('next-label') %>
  </div>
</div>

app/views/admin/brands/new.html.erb
<!--=== 新增品牌 ===-->
<h2><span class="fa fa-file-text-o"></span> <%= t('brand-new') %></h2>
<%= render('form') %>

app/views/admin/brands/show.html.erb
<!--=== 品牌資訊 ===-->
<h1> <%= @brand.name %> </h1>

<h3><%= t('f-brand-logo') %></h3>

<p>
  <% if @brand.logo.present? %>
    <%= image_tag(@brand.logo.other.url) %>
  <% else %>
    <%= t('notice-no-image') %>
  <% end %>
</p>

<h3><%= t('f-brand-description') %></h3>
<p>
  <%= simple_format(@brand.description) %>
</p>

<h3><%= t('f-brand-products') %></h3>
<% @brand.products.each do |product| %>
  <li><%= link_to(product.name, admin_product_path(product)) %></li>
<% end %>